### ISSUE TITLE
Could it support the `datefmt` for `formatter`?

### ISSUE THREAD

**Issue by afunTW** [BNMetrics/logme#5]
Appreciated to make the logging function easier.
However, it seems not support to modify the `datefmt` in logme.ini?

https://github.com/BNMetrics/logme/blob/master/logme/providers.py#L243-L248

Wish to implement the `datefmt` in the future.
```python
logger.Formatter(..., datefmt='%Y-%m-%d %H:%M:%S')
```

**Comment by BNMetrics** [comment]
Hi @afunTW,

That's actually a great idea! I'm going to implement this and have it ready for the next version! :)

Thank you so much for the suggestion! 👍

**Comment by afunTW** [comment]
Hi @BNMetrics ,

Thanks to your contribution. It seems a simple feature but helpful.
If possible I would like to ask for the documentation about testing flow. It's good for collaboration and PR.

**Comment by BNMetrics** [comment]
Hi @afunTW ,

I'm glad I could help! :)
I'm not exactly sure what you meant by testing flow? do you mean about how to test when using this package or something else?

If you could specify, that would be amazing! :)

Thank you!

**Comment by BNMetrics** [comment]
Hi @afunTW,

Oh I see! :)
If you are to add the `datefmt`, you wouldn't need to have to test the logging anymore, because all the functionality of logme is coverred by its own tests. :)
So with that said, you only need to test your code, and don't have to test anything related to logme.

I actually updated the code so your suggestion is in there now! :)
I will add the documentation and update the version today.

**Comment by BNMetrics** [comment]
Version updated(1.3.0)! Now you can have custome `datefmt` and `style` in logme.ini. :)
